name: ESLint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.5.1'  # Choose the Node.js version you need

    - name: Install dependencies
      run: npm install
    
    - name: Update permissions for ESLint
      run: chmod +x ./node_modules/.bin/eslint
    
    - name: Run ESLint
      run: npm run lint

    - name: Update permissions for jest
      run: chmod +x node_modules/.bin/jest

    - name: Run Jest Tests
      run: npm test
